### ISSUE TITLE
Live reload stops working

### ISSUE THREAD

**Issue by elax102** [pingyhq/pingy-cli#10]
I'm not exactly sure what is causing live reload to fail. My current suspicion is it'll stop working after editing the scss files a few times but I'm not entirely sure. I'm using Chrome on Arch. I don't get any console errors. Refreshing the page doesn't work. Emptying cache and hard reload doesn't work. So far the only way to fix it is to restart pingy dev. I've uploaded [my project](https://github.com/elax102/Pingy-Test) so you can take a look yourselves. Please let me know if you need more info. Thanks!

**Comment by davej** [comment]
Thanks for taking the time to upload your repo. I've tried my best to recreate your bug but I can't (I spent 15 minutes randomly changing styles).

I have a feeling that this may be a Sass bug that is specific to your architecture. I've seen bugs like this pop up before on Sass, as it is a native dependency it can be very difficult to debug.

Sorry about this, I'm not sure where to go from here. In future versions I'll try to add a `--debug` that will print out more to the console. If you can also recreate this bug on a non-sass project let me know.

Thanks for the bug report, sorry I couldn't help more.
