### ISSUE TITLE
Usage examples / documentation for WordPress development?

### ISSUE THREAD

**Issue by ronilaukkarinen** [pingyhq/pingy-cli#12]
Would love to use pingy with WordPress development. We have [our own gulp setup](https://github.com/digitoimistodude/devpackages) running on [our own vagrant box](https://github.com/digitoimistodude/marlin-vagrant) and the paths/settings for files are quite different than pingys defaults and there's not much documentation available.

Is pingy-cli intended only for HTML/Jade/Pug/ejs, not php/other? I understand "minimal configuration" perspective, but there are scenarios that require some sort of definitions.

How to get started with pingy + WordPress or is it even intended usage case or possible?

**Comment by davej** [comment]
Yeah, not for the moment. In the future, it might be possible to proxy through to a PHP server but right now I want to keep it simple. If you were using the Wordpress JSON API then that's a different story, Pingy could work well for that.

I think it's probably best to stick to Gulp for what you're doing right now. :)

**Comment by ronilaukkarinen** [comment]
OK, thanks a lot for the input! appreciate it.
