### ISSUE TITLE
Export error 4058

### ISSUE THREAD

**Issue by Makanz** [pingyhq/pingy-cli#15]
When I try to export my project I´ve got error nr 4058.
I´m running Windows 10, Node.js v6.9.1

![pingy-cli-error](https://cloud.githubusercontent.com/assets/4232943/25992451/dac575f0-3706-11e7-98ca-f3fd1386a24e.PNG)

{ Error: ENOENT: no such file or directory, open 'C:\Temp\Pingy-test\$stdin' at Error (native)
errno: -4058,
code: 'ENOENT',
syscall: 'open',
path: 'C:\\Temp\\Pingy-test\\$stdin' }

**Comment by davej** [comment]
Just did a quick test with Windows 7 and Node `6.10.3` and everything seemed ok. What kind files are you exporting? (i.e.. Sass? Less? Babel?)

**Comment by Makanz** [comment]
I have now upgraded Node to version 6.10.3 but I still get the same error 4058. 
index.html and Less, it works well with "pingy dev" but not on export.

**Comment by davej** [comment]
Is it just one Less file or does the Less file import other Less files? If you delete the less file (temporarily) will `pingy export` work then? I'll try and replicate your setup and get this issue fixed for you.

**Comment by davej** [comment]
If it's possible to create a zip up a version of the site (no need to include `node_modules`) it might be easier to debug what's going on.

**Comment by Makanz** [comment]
The problem was caused by an import of bootstrap in my .less file. 

What is the best way to include, for example, jquery and bootstrap?

**Comment by davej** [comment]
If you can't include bootstrap the normal way then it's a bug. Also the error description was not helpful. 

I'm on holidays for a couple of weeks but I'll fix this when back.

**Comment by Makanz** [comment]
main.less

`@import "bower_components/bootstrap/less/bootstrap.less";

@heading-color: #2284bf;

body {
		font-family: Arial, sans-serif;
		background-color: #CCC;
}

.container {
	height: 100vh;
	background-color: #FFF;
	box-shadow: 0 0 20px 5px rgba(0,0,0,.2);
}

h1, h2 {
	color: @heading-color;
}
`

**Comment by neberaa** [comment]
Have the same problem with export... I used scss import.

**Comment by Snailsloth** [comment]
same here with export while importing stylus

**Comment by ladislavsulc** [comment]
Same here with scss import (uikit).

**Comment by davej** [comment]
Thanks for the reports.
Is everybody that has experienced this on Windows?

**Comment by davej** [comment]
I'm closing this for now. If someone can give me a link to a repository where I can reproduce this using Pingy `v0.8.1` then I'd be happy to re-open and fix it.

**Comment by Snailsloth** [comment]
@davej Hello! Just got this error while exporting project with stylus imports. Pushed it to [this repo](https://github.com/Snailsloth/pingy-export-error)
`√ Compiling index.pug
√ Compiling main.js
√ Compiling particle-app.js
√ Compiling particles.js
√ Compiling _base.styl
× Failed export to D:/GIT/home/ehloworld/dist
{ Error: ENOENT: no such file or directory, open 'D:\GIT\home\ehloworld\$stdin'
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'D:\\GIT\\home\\ehloworld\\$stdin' }`

Win7Pro x64, Node v8.7.0, pingy 0.9.3.
if it's not too late - take a look please, thank you!

**Comment by davej** [comment]
@Snailsloth Thanks for the test repo. I will work on this later in the week.

**Comment by davej** [comment]
@Snailsloth: Ah, it's a source map issue. I'll work on a fix tomorrow. If you want a quick fix in the meantime then you can add `"sourceMap": false,` to your `pingy.json`.

**Comment by Snailsloth** [comment]
@davej 
Thank you so much for your work, everything is awesome now.

**Comment by davej** [comment]
@Snailsloth: thank you for the repo, makes it much easier to figure out what the bug is.

**Comment by davej** [comment]
In v0.9.4 this should be fixed even with source maps turned on.

https://github.com/pingyhq/pingy-cli/releases/tag/%40pingy%2Fcli%400.9.4
