### ISSUE TITLE
Pingy Setup Questions - What do they mean?

### ISSUE THREAD

**Issue by randallmlough** [pingyhq/pingy-cli#16]
Why do you ask 'entry point' and 'test script' and what does those do and why are you asking these questions? I'm just starting down the path of webdev and would like to know why this is an important question to know. It may be helpful in the Readme file to give an overview of the questions that you are asking and why X question is important to know for us curious people :)

**Comment by davej** [comment]
These are npm things. For a Pingy project you can basically ignore them and choose the defaults. Pingy requires a `package.json` so if you don't have one already then it will run `npm init` which is where those questions come from.

* Entry point/main: https://docs.npmjs.com/files/package.json#main
* Test Script: https://docs.npmjs.com/misc/scripts
