### ISSUE TITLE
Switch to `npm init --yes`

### ISSUE THREAD

**Issue by davej** [pingyhq/pingy-cli#18]
`npm init` is confusing for people not familiar with npm (#16). Consider switching to `npm init --yes` instead.

**Comment by filtercake** [comment]
this would be great! 👍 

i started working on a small tutorial on how to use pingy for rapid browser prototyping and put an `npm init --yes` before the `pingy init` to reduce config...

**Comment by davej** [comment]
Awesome please do share when published 👍

If you feel like PRing this then go right ahead, should be reasonably straightforward. Would be good to have a flag `--npmInit` for the old behaviour too.

**Comment by davej** [comment]
Actually now that I think about it... It's best to dump the old behaviour altogether. If people want to run `npm init` then it's better to run it themselves manually rather than adding bloat to Pingy CLI.

**Comment by filtercake** [comment]
> If people want to run `npm init` then it's better to run it themselves manually rather than adding bloat to Pingy CLI.

👍

**Comment by davej** [comment]
added in v0.6.8: https://github.com/pingyhq/pingy-cli/releases/tag/%40pingy%2Fcli%400.6.8
