### ISSUE TITLE
Live reload on change of Pug/Jade Partials

### ISSUE THREAD

**Issue by davej** [pingyhq/pingy-cli#19]
Currently, this doesn't work. Needs to be fixed.

**Comment by filtercake** [comment]
i made a workaround by watching pug and sass partials with nodemon and then `touch`ing the `index.pug`.

so after installing [nodemon](https://nodemon.io/), i changed my `package.json` to this:

```json
  "scripts": {
    "start": "npm run dev & npm run force-render-watch",
    "dev": "pingy dev",
    "export": "pingy export",
    "force-render-watch": "./node_modules/.bin/nodemon --ext pug,sass --ignore node_modules/ -x 'touch index.pug'"
  },
```

it is slow but it works...

**Comment by davej** [comment]
Awesome @filtercake. Is there a reason why you've included sass files in the watchlist extensions? Does Pingy live reload not work with sass for you?

**Comment by filtercake** [comment]
> Is there a reason why you've included sass files in the watchlist extensions?

yes, I am stealing [vue's concept of single file components](https://vuejs.org/v2/guide/single-file-components.html). in my pug component partials i have a block like this:

```sass
style
  :sass
    @import components/shared
    $some-local-variable: 1em
    .some-class
      @include mixin-from-shared
      padding: $some-shared-variable
      margin-bottom: $some-local-variable

```

so if i change things in the shared sass partial, I want to trigger a complete re-render of all the things to make sure I see all effects.

**Comment by davej** [comment]
Nice.

I'll look into this use case and try and figure if there's a way CLI can support it without requiring explicit configuration of the source directories.

**Comment by davej** [comment]
Pug/Jade reloading added in v0.6.8: https://github.com/pingyhq/pingy-cli/releases/tag/%40pingy%2Fcli%400.6.8
