### ISSUE TITLE
Pug/Jade source copied to build folder

### ISSUE THREAD

**Issue by phillyDesignr** [pingyhq/pingy-cli#20]
For me I see no reason or value to copy the source pug/jade files to the build folder and would ultimately remove them if I was throwing the build on a server. 

Maybe could be an option that is false by default.

**Comment by davej** [comment]
I'm closing this because it's not something I plan to support in the short-term, I may revisit it though.

If you want a quick-fix then you could do something like this with your package.json export script:

```
	"scripts": {
		"start": "pingy dev",
		"export": "pingy export && find ./dist/ -name \"*.pug\" -type f -delete"
	},
```

**Comment by mazadah** [comment]
Is this workaround still valid? doesn't seem to work anymore:
`"export": "pingy export && find ./dist/ -name \"*.css\" -type f -delete"`
I am still intrested in an option like this:
`{
    //...
    "sourceMap": false,
    //...
}
`

**Comment by davej** [comment]
> Is this workaround still valid?

It depends on your OS. If you're on windows then you probably want something like: `pingy export && del /s *.css`. See here for more info: https://stackoverflow.com/questions/35957077/how-to-remove-all-files-with-specific-extension-in-folder

**Comment by mazadah** [comment]
The "del" command works by itself. But if I use it with pingy export, it's not.
I think it is executed before the "export" is completed. So the files are created after the del command.

**Comment by davej** [comment]
I'm guessing you're using powershell or something. See here: https://stackoverflow.com/questions/563600/can-i-get-to-work-in-powershell

**Comment by mazadah** [comment]
Thanks!
