### ISSUE TITLE
Support for Reshape

### ISSUE THREAD

**Issue by insanetisane** [pingyhq/pingy-cli#22]
I know this is probably a long shot but support for [Reshape](https://github.com/reshape/reshape) would be amazing. It's like Postcss but for HTML.

**Comment by davej** [comment]
Probably not anytime soon. I'm trying to keep Pingy low/no-config and focus on that for the moment. Babel and possibly PostCSS are exceptions because they are already very popular. I'll keep this open for the moment but I probably won't be working on it in the next few months. Happy to take PRs though.

Reshape does look very cool though.

**Comment by insanetisane** [comment]
Hmmm ok I may give it a shot. Where should this be implemented in the codebase? baby-tolk? Also I noticed accord is being used. Reshape is actually by the same author! So it may make sense to get it connected to accord?

**Comment by davej** [comment]
Yup, accord is where it needs to be added. Then it would just be a case of adding it to the whitelist in baby tolk. Also check out spike by @jescalan, that build tool might be more to your liking if you want something with a bit more configuration than Pingy CLI. 🙂

**Comment by insanetisane** [comment]
hah it's funny you say that, I've been playing around with Spike as well! Its a great project! What I like about Pingy cli is the in-memory compilation (for speed esp. on bigger builds) and i'm really liking the sounds of the Pingy platform yet to come. Decisions decisions.... ;P

**Comment by jescalan** [comment]
Hi! Since spike uses webpack as its core compiler, I think you'll find that it's quite fast even on larger builds. That being said, I also love pingy, they are just great for different use cases. Thanks for the shout out @davej 😁

**Comment by davej** [comment]
Closing for the moment. Feel free to reference this in a PR but it's not in my short-term plans.
