### ISSUE TITLE
Export Error -2

### ISSUE THREAD

**Issue by randallmlough** [pingyhq/pingy-cli#25]
On export I'm getting the following error
![Error Screenshot](https://cloud.githubusercontent.com/assets/25895389/26077908/905c47c8-3972-11e7-891a-9c94d8082c6f.png)

I'm using standard HTML, Sass and standard JS. I also tried to manually create the dist folder and it was deleted on the following export command. I believe all my npm versions are up-to-date.

**Comment by davej** [comment]
Possibly related to #15. I'll look into this when I'm back from holiday in early June.

**Comment by davej** [comment]
@randallmlough: Are you still experiencing this issue with Pingy 0.8.1? If you are then could you give me a link to a repo where I can reproduce this.

**Comment by davej** [comment]
Closing this because I can not recreate it. Feel free to ping me if anybody is still encountering this error on the latest version and I'll reopen.
