### ISSUE TITLE
Use yarn instead npm for install plugins

### ISSUE THREAD

**Issue by germaniuz** [pingyhq/pingy-cli#26]
Is it possible to use yarn instead of npm for install plugins in pingy init (it increases install speed)

**Comment by davej** [comment]
Makes sense! I'm on holidays at the moment so can't do this right now. Will take a PR though. For the moment you can just choose 'no' for install and do it manually.

**Comment by germaniuz** [comment]
Thanks for quick responce! Cool to see this feature)

**Comment by davej** [comment]
Added in [0.6.10](https://github.com/pingyhq/pingy-cli/releases/tag/%40pingy%2Fcli%400.6.10). You can now do `pingy init --yarn` to install packages with Yarn instead of NPM.
