### ISSUE TITLE
Error when import scss file to main scss file.

### ISSUE THREAD

**Issue by huyle2607** [pingyhq/pingy-cli#28]
I'm currently using Pingy for a simple project. I tend to divide scss file into multiple files then import it to a sort of main.scss file, it's easier for maintenance later. But I encounter a problem that when I save in child file, it said error. When I open main.scss file and save, everything worked fine.

Here is the error
![screenshot_1](https://cloud.githubusercontent.com/assets/15210474/26138740/7ed107da-3af5-11e7-8229-47830b79f768.png)

Here is my structure for the styles folder.
![screenshot_2](https://cloud.githubusercontent.com/assets/15210474/26138750/9204f6fe-3af5-11e7-8585-13f11592eeae.png)

**Comment by davej** [comment]
What is your import code like? Did you include the underscore (_) in the import?

**Comment by huyle2607** [comment]
No! It's something like this 
`@import './fonts';
 @import './fonts';`

**Comment by davej** [comment]
Shouldn't it be this instead?

```
@import './_404';
```

**Comment by huyle2607** [comment]
It worked! But I have to save on _404.scss then back to main.scss and save one more time. It did not watch the _404.scss file :|

**Comment by davej** [comment]
Hmm but if you restart the `pingy dev` server then it works ok again and watches the correct files, right?

**Comment by maxcaluva** [comment]
I'm doing it like this and it works for me

![image](https://cloud.githubusercontent.com/assets/18628784/26280999/3d3deb8c-3dbe-11e7-8ae6-3ee2388ae6a5.png)

**Comment by S3B4S** [comment]
Unfortunately I have the same issue, I've tried multiple things, even recreating @maxcaluva his project structure but pingy doesn't watch the partials for me. I have to go back and save at `main.scss` if I want to have my changes in the partials to be compiled.

Project structure:
```
├── index.html
├─┬ scripts
│ └── main.js
└─┬ styles
  ├─┬ components
  | └── _contact.scss
  └── main.scss
```
`@import "./components/contact";` is used inside main.scss

Sidenote (minor issue): The first save never seems to work for me, wherever used, after that the second save and onwards will compile the scss.

**Comment by davej** [comment]
@S3B4S: Hoping this has been fixed for you now. Could you retest using Pingy 0.8.1, let me know if you're still having problems and I'll reopen this issue.

**Comment by S3B4S** [comment]
Sorry for the delay in the response, everything seems to be resolved. Good job! 👍

**Comment by davej** [comment]
@S3B4S great, thanks for testing.
