### ISSUE TITLE
custom scaffolds

### ISSUE THREAD

**Issue by filtercake** [pingyhq/pingy-cli#35]
i wonder what the quickest workaround would be for now to customize the scaffolding of a pug/sass project.

specifically i would want to have...

- installed `jstransformer-sass' do enable [style tags being written in sass](https://pugjs.org/language/filters.html)
- a components folder
- a `shared.sass` file inside that
- an example component file with the mentioned sass style tag and example import of `shared.sass`
- have that component included in the index.pug

i guess for now i can just make a repo of my boilerplate and clone that... just wondering if there is a better way you would recommend?

---

ideas for the future:

- `pingy init --scaffold [ username/reponame || github_url ]` to pull from github. pingy could read all config as it does in compile mode and skip the user questions.

- `pingy list scaffolds` could pull repos via the github API which follow a naming pattern convention like `pingy-scaffold-<html_abstraction>-<css_abstraction>-<js_abstraction>-<whatever>-<you>-<want_to_add>`.

- on the other hand, a *curated* list could be returned on `pingy list scaffolds` to keep it short and helpful, while something like `pingy listall scaffolds` could do the mentioned github search...

**Comment by davej** [comment]
Yes, for sure. This will happen, may take a bit of time though as I work through the other issues.

**Comment by davej** [comment]
Pingy CLI now supports custom scaffolds in [`v0.10.0`](https://github.com/pingyhq/pingy-cli/releases/tag/%40pingy%2Fcli%400.10.0)!

If anybody is interested in creating your own scaffold then [here are some instructions](https://github.com/pingyhq/pingy-cli/wiki/Creating-a-custom-scaffold). You can also join me in the new [Gitter chat channel](https://gitter.im/pingy-cli/Lobby#) for some help. I've also created a reference scaffold: [bootstrap-jumbotron](https://github.com/pingyhq/pingy-scaffold-bootstrap-jumbotron).

This is just the start. Scaffolds will be one of the defining features of Pingy and there are genuinely unique scaffolding features that will be added in upcoming releases.

**Comment by filtercake** [comment]
😻

**Comment by davej** [comment]
`@pingy/cli@0.11.0` just released and it brings two new scaffolding features:
* Beta web scaffolds, really excited about this, it's genuinely new. Docs will come later but follow the steps here to see what it's all about: https://github.com/pingyhq/pingy-scaffold-bootstrap. As usual if anybody wants to create their own web scaffold then I'm here to help. 😊
* Alias support with [`pingy scaffold [alias]`](https://github.com/pingyhq/scaffolds).

**Comment by davej** [comment]
Some Web Scaffolding docs here: https://github.com/pingyhq/pingy-cli/wiki/Creating-a-Web-Scaffold

**Comment by filtercake** [comment]
that is so amazing <3

i am currently working on our design system setup at work. I planned to use pingy scaffold anyways for prototyping, but this opens up *a lot* of possibilitites...

i am also thinking how this could work together with something like [react-sketchapp](https://github.com/airbnb/react-sketchapp). i am very weary though personally of strictly tying myself to a framework/libray like React. Not to mention all the overhead that brings for prototyping...

still: if you think having something like [Nucleus](https://holidaypirates.github.io/nucleus/)* built into a scaffold, and then packaging it all together into an electron app... whoa. designers could render every component onto their artboards, always synced to production code, without CLI usage, and no need to maintain a sketch library anymore 😮

definitely off-topic now, sorry.

* I have issues with some nucleus-specific details, but so far it is closest to what i have in mind...

**Comment by davej** [comment]
@filtercake 

Really interested in this area. I can definitely see the potential for Pingy in the DesignOps space but I don't have any experience there. If you you have ideas for features I could add that would make it easier to create a DesignOps scaffold then give me a shout. This is a soft beta launch for Web Scaffolds, the official launch will be in early January but I really want to explore all possibilities before then.
