### ISSUE TITLE
Support for markdown files

### ISSUE THREAD

**Issue by insanetisane** [pingyhq/pingy-cli#37]
I realized a little while ago that Pingy is a lot like [Harpjs](http://harpjs.com/). 
Pingy is more modern of course and has support for Babel and friends, live reload etc.. which is awesome. I'm just wondering if there's any plan for supporting Markdown files, similar to Harp (and most other static site generators).

**Comment by davej** [comment]
It's actually supported but not publicised. Just do `npm install marked` And use the `.md` extension. 🙂

**Comment by insanetisane** [comment]
Oh! sweet. Thanks!

**Comment by jomko** [comment]
Hi, @davej. First of all thank you for Pingy.
Can you explain how to use `marked` with jade?
In my project I have file about.jade and when I rename it to about.md and try to open in browser by http://localhost:60740/about I get `Cannot GET /about` and at http://localhost:60740/about.html I see source code jade, not compiled at html. Renaming this file to about.jade.md give me `Cannot GET /about.html`
Thank you!

**Comment by davej** [comment]
Currently a file can be markdown or jade. It cannot be both.

**Comment by jomko** [comment]
Thanks for answer. Maybe I have poorly explained or I'm looking for my answer in wrong place.
What I try to figure out it's run in browser other file than `index.jade`, it's mean my project has several pages.

**Comment by davej** [comment]
@jomko Sorry I still don't understand. Do you have a link to a repo?

**Comment by jomko** [comment]
Hi, @davej. My project is simple, and look like this
![111](https://user-images.githubusercontent.com/2182831/29865608-9c4f9804-8d7e-11e7-9bdd-6c7bd2ec1998.jpg)
File about.jade is just a copy of index.jade (for the present, just fot testing). How open this file in browser? At http://localhost:60740/about I get `Cannot GET /about`.
Thank you!

**Comment by davej** [comment]
Does http://localhost:60740/ work and compile the jade file?

**Comment by davej** [comment]
Hmmm, that may be a bug, http://localhost:60740/about should not work but http://localhost:60740/about should work. Can you try moving `about.jade` to `/about/index.jade` and then requesting http://localhost:60740/about?

What version of Pingy CLI are you using?

**Comment by jomko** [comment]
It is Pingy 0.6.14
Moving about.jade to /about/index.jade works like a charm, and it is solution for me.
Thank you!

**Comment by davej** [comment]
Cool, I'll reopen this and investigate why http://localhost:60740/about.html didn't work for the next version.

**Comment by davej** [comment]
I believe this is now fixed. If you're still experiencing this issue with Pingy 0.8.1 then let me know and I'll re-open.
