### ISSUE TITLE
keep auto-reload on error pages

### ISSUE THREAD

**Issue by filtercake** [pingyhq/pingy-cli#38]
![image](https://cloud.githubusercontent.com/assets/170145/26673642/ec36f554-46bd-11e7-835d-f6b1db4c3cd1.png)

it's cool that pingy inlines errors to the frontend 👍 

maybe it would be possible to append the reload-watcher to that, so that it auto-reloads a fixed version too.

**Comment by davej** [comment]
Agreed 👍

**Comment by davej** [comment]
This seems to now work. Perhaps I fixed this and forgot. 😀
Tested with Pug in latest Chrome and Firefox. If there's some combination of compiler + browser that doesn't work for you then let me know and I'll reopen.
