### ISSUE TITLE
Add autoprefixer

### ISSUE THREAD

**Issue by sakamies** [pingyhq/pingy-cli#41]
Like Babel for javascript, Autoprefixer for CSS would be super useful. It's pretty much [standard practice](https://developers.google.com/web/tools/setup/setup-buildtools#dont_trip_up_with_vendor_prefixes) nowadays.

**Comment by sakamies** [comment]
Oops, sorry for #9 dupe.

**Comment by davej** [comment]
Yes, let me know if you have any issues with it. :)
