### ISSUE TITLE
Option to disable .shas.json

### ISSUE THREAD

**Issue by borekb** [pingyhq/pingy-cli#43]
Is it possible to avoid putting `.shas.json` into my dist folder? I always regenerate everything fresh (I run `rm -rf dist` before `pingy export` to be sure there are no leftovers).

**Comment by davej** [comment]
Probably not going to do this.

A bit like #20, I'd recommend editing your `npm run export` script. Something like:

```
"scripts": {
  "start": "pingy dev",
  "export": "rm -rf dist && pingy export && rm dist/.shas.json"
},
```

If `pingy export` is leaving leftovers from the previous export then that is a bug and you can create an issue for it.

**Comment by borekb** [comment]
Agree, you're right.
