### ISSUE TITLE
refresh does not seem to work when editing ejs child partials 

### ISSUE THREAD

**Issue by asokani** [pingyhq/pingy-cli#46]
Not sure if doing things correctly. This is a sample project: https://github.com/asokani/pingy-test

When I have `yarn pingy dev` running and doing changes in _content.ejs, the page is not reloaded. Changes inside index.ejs are visible immediately.

**Comment by asokani** [comment]
I tried another clean computer, and there was a bug in my demo. It's now fine. But the problem remains. Anyone experiencing it too?

**Comment by davej** [comment]
Can you try a fresh `rm -rf node_modules && yarn install`. I'm not able to recreate this issue.

**Comment by asokani** [comment]
I am able to reproduce the problem I'm experiencing with clean docker image:

1. mkdir -p /tmp/pingy-test && cd /tmp/pingy-test
2. run `sudo docker run --rm -i -t -v /tmp/pingy-test:/opt/pingy-test -p 9000:9000 node:8.1.4 bash`
3. run (inside the docker) ` cd /opt/pingy-test && git clone https://github.com/asokani/pingy-test . && yarn install`
4. run (inside the docker) `yarn pingy dev`
5. open your browser at `http://localhost:9000/` 
6. try to edit `/tmp/pingy-test/index.ejs` --> page updates immediately
7. try to edit `/tmp/pingy-test/_content.ejs` --> page is not updated

**Comment by neberaa** [comment]
The same problem,  but with scss partials.!!

**Comment by neberaa** [comment]
also index. pug does not refresh too....

**Comment by davej** [comment]
I see what's going on here, I'm working on a fix and improving the test suite so this doesn't happen in the future. In the meantime you can access `http://localhost:9000/index.html` directly instead of `http://localhost:9000/` and it should work.

**Comment by davej** [comment]
Fixed in 0.6.14.
