### ISSUE TITLE
pingy export fails to update "dist" even there are new changes

### ISSUE THREAD

**Issue by asokani** [pingyhq/pingy-cli#47]
Not sure if doing things correctly. This is a sample project: https://github.com/asokani/pingy-test

When I do `yarn pingy export`, it exports the page correctly. After making some changes inside index.ejs and doint `yarn pingy export` again, it outputs this:

    yarn pingy v0.24.6
    $ "/home/main/Projects/pingy-test/node_modules/.bin/pingy" export
    0.6.13 (local)
    ..
    ✔ Exporting to /home/main/Projects/pingy-test/dist
    Done in 2.45s.

and `index.html` is not updated.

**Comment by asokani** [comment]
I tried another clean computer, and there was a bug in my demo. It's now fine. But the problem remains. Anyone experiencing it too?

**Comment by davej** [comment]
Ok, so both #46 and #47 work fine on a clean install but not on your existing install. Is this correct?

**Comment by asokani** [comment]
No. The demo itself was broken. Now it's not, but the reported problem still exists. Even on the clean install. Maybe I'm doing something wrong, I'll try a different approach and let you know. Thanks.

**Comment by asokani** [comment]
I am able to reproduce the problem I'm experiencing with clean docker image:

1. mkdir -p /tmp/pingy-test && cd /tmp/pingy-test
2. run `sudo docker run --rm -i -t -v /tmp/pingy-test:/opt/pingy-test -p 9000:9000 node:8.1.4 bash`
3. run (inside the docker) ` cd /opt/pingy-test && git clone https://github.com/asokani/pingy-test . && yarn install`
4. run (inside the docker) `yarn pingy export`
5. try to edit `/tmp/pingy-test/styles/main.scss` 
6. run (inside the docker) `yarn pingy export` again --> it outputs only pingy logo and `✔ Exporting to   /opt/pingy-test/dist, Done in 1.28s.`
7. open `/tmp/pingy-test/dist/styles/main.css` --> the change from (5) is not there

**Comment by davej** [comment]
@asokani: This should be fixed in `v0.8.1`. Please run `yarn upgrade @pingy/cli@0.8` and let me know if you still have any issues.
