### ISSUE TITLE
styleguide generator

### ISSUE THREAD

**Issue by filtercake** [pingyhq/pingy-cli#49]
what I want is something that generates a styleguide – ideally something like [postcss-style-guide](https://github.com/morishitter/postcss-style-guide) or [mdcss](https://github.com/jonathantneal/mdcss) which parses CSS comments.

Before I try stuff out though I wondered if you can recommend something... maybe you tried this out yourself already... and how would you integrate it into a freshly generated pingy project...

thx,
Fabian

**Comment by davej** [comment]
No tips for the moment, this will be possible when I get around to implementing #14 though.
