### ISSUE TITLE
Custom project structure

### ISSUE THREAD

**Issue by S3B4S** [pingyhq/pingy-cli#52]
I'm currently trying to setup a boilerplate project which has a different file structure than what is proposed by `pingy init`: 
```
├── index.html
├─┬ scripts
│ └── main.js
├─┬ styles
  └── main.scss
```
If my file structure would look like this for example:
```
├── index.html
├─┬ js
│ └── main.js
├─┬ src
  └── main.scss
```
Would it be possible for me to change the `src` and `dist` through `.pingy.json`?
```json
{
  "js": {
    "src": "src/js",
    "dist": "dist/js"
  },
  "css": {
    "src": "src/scss",
    "dist": "dist/scss"
  }
}
```

**Comment by davej** [comment]
Your project can have whatever structure you like, Pingy does not rely on the folder names being fixed, you can rename them if you like.

**Comment by S3B4S** [comment]
Oh! Thought it'd create a seperate folder and host it from there, I was wrong in that, thanks! I'm encountering an other issue now though, which is related to #28, I've commented there to keep things tidy :)
