### ISSUE TITLE
Compiling HTML from Pug exports the Pug files during `pingy export`

### ISSUE THREAD

**Issue by cdunlap** [pingyhq/pingy-cli#53]
Is it normal to export the *.pug files along side the exported HTML? I attempted to add the pug files to the exclusion rules but that ended up preventing them from being compiled. Is that a bug or is it because I used the wrong options?

Here's what I used in the `exclusions` key to attempt to exclude *.pug from being copied over during export.
`{
			"path": "*.pug",
			"action": "exclude",
			"type": "file"
		}`
This resulted in the HTML not being built at all.

Effectively, I want the Pug files to compile, but not get copied over into `dist`. Is that possible? Easy enough to work around right now by simply deleting them from the output but since they're source files, I don't feel that they should be exported in the first place.

Same thing goes for *.scss files (related?)

**Comment by davej** [comment]
See #20. Exclusions is only for excluding input files, not output files.

**Comment by cdunlap** [comment]
Thank you!

Sorry for the duplicate.
