### ISSUE TITLE
Global config?

### ISSUE THREAD

**Issue by borekb** [pingyhq/pingy-cli#67]
I know this goes a little bit against the "zero configuration" mantra but I'd appreciate a way to tell Pingy to launch Chrome Canary via some global setting . My current workflow is to let Pingy launch my default browser (Chrome stable), then open Canary manually and open the site there. I know about `pingy dev --no-open` but opening a browser of my choice would be nicer.

I imagine something like `~/.pingy.json` and this in it:

```json
{
  "pingy": {
    "browser": "path/to/chrome/canary"
  }
}
```

**Comment by davej** [comment]
Thanks for the request. Unfortunately this is a little bit too specific right now. If there's more demand then I might consider it in the future.
