### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'globals.css'

### ISSUE THREAD

**Issue by dunepebbler** [pingyhq/pingy-cli#69]
Hi,
Pingy export yielded this error:

```
✖ Compiling globals.styl
{ Error: ENOENT: no such file or directory, open 'globals.css'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'globals.css' }
✖ Failed export to /[path]/dist
```

Adding `"sourceMap": false,` fixes the problem, but I'm wondering what's going wrong here.

I'm running 0.9.5, but the site was initialised with a 0.6.x version

[View repository here](https://github.com/dunepebbler/Pingy-errno--2)

**Comment by davej** [comment]
Thanks for the repo, it makes it much easier to debug. It's a strange issue with Stylus + `autoprefix` + `sourceMap`. I've just pushed a fix so it should work if you update to `@pingy/cli@0.10.3`.

Another little tip is that you can rename files that aren't compiled directly with an `_` prefix and Pingy will ignore them when exporting. E.g.. `_globals.styl`. I really should do a better job of documenting this stuff. 🙂
