### ISSUE TITLE
[scaffold] not rendering index.pug from scaffold

### ISSUE THREAD

**Issue by filtercake** [pingyhq/pingy-cli#72]
first of at all: super amazing work with the scaffolding! <3

I followed [my own feature request](https://github.com/pingyhq/pingy-cli/issues/35) and created [pingy-scaffold-pug-sass](https://github.com/filtercake/pingy-scaffold-pug-sass).

starting `pingy dev`, the browser displays `cannot get /` though.

when i rename the file to `index.html`, it is served fine.

**Comment by davej** [comment]
Awesome. I think you just need to add pug to you devDependencies in pingy-scaffold.json:

```
"devDependencies": {
  "pug": "",
  "node-sass": "^4.5.3",
  "jstransformer-sass": "1.0.0",
  "jstransformer-markdown-it":"2.0.0"
},
```

You can put in a version of `2.0.0-rc.4` if you prefer. It's a bit weird because `v2` of Pug hasn't been released yet.

**Comment by filtercake** [comment]
thx, i see. i thought it would add the ones which are included with init automatically.

will add a hint to the wiki...

**Comment by davej** [comment]
Thanks for trying this out. Any feedback is appreciated. 👍 

> thx, i see. i thought it would add the ones which are included with init automatically.

Yes, it does for `pingyJson`, it will use the folder name when you scaffold the site. Those fields are just used to describe the scaffold you are using in the CLI (see screenshot below):

![image](https://user-images.githubusercontent.com/26971/33185192-d5e5f260-d078-11e7-8a78-ceeb914df602.png)

**Comment by filtercake** [comment]
i'm not sure i fully get it :)

i added the hints to the wiki: https://github.com/filtercake/pingy-cli-wiki/blob/master/Creating-a-custom-scaffold.md (also added the mandatory fields mentioned in #71)
