### ISSUE TITLE
Occasionally crash

### ISSUE THREAD

**Issue by wingliu0** [pingyhq/pingy-cli#78]
The hot-reload function will occasionally crash 

Steps to reproduce:
1. init a project using pingy-cli
2. choose to use scss compiler
3. edit scss file
4. occasionally, an error message will be logged in chrome and no more hot-reloading unless reloading the page.

![screen shot 2017-12-05 at 1 22 50 pm](https://user-images.githubusercontent.com/10822238/33591354-1de0ce82-d9c0-11e7-8fd4-841b9ed33209.png)

**Comment by davej** [comment]
What OS and version of Pingy are you using?

**Comment by wingliu0** [comment]
0.10.4 (local)
OSX 10.11.2

**Comment by davej** [comment]
Thanks. Just released a fix. Should work ok now in `v0.11.1`.

**Comment by wingliu0** [comment]
I cant find the update in npm

**Comment by wingliu0** [comment]
got it, i made a typo..
