### ISSUE TITLE
global node-sass

### ISSUE THREAD

**Issue by indus** [pingyhq/pingy-cli#8]
I´m using sass in all my projects. Can you provide a way to check for the global install and then just link?

**Comment by davej** [comment]
The problem with this is that your project won't be portable. The idea is that your project should work simply after doing `npm install && npm start`. This would break that. It would also get messy if Sass starting introducing backwards incompatible changes. Let me think about it for a while.

**Comment by indus** [comment]
I understand your point, but to be honest I really don´t get the whole npm thing when it comes to tooling. I just feels wrong to me to install uglifyjs, tsc, node-sass (or any other tool that I call from CLI) a hundret times for every tiny project - I don´t even want to install these tools more then once and I really don´t see a need to. Just like I don´t install a new IDE for every new project. Just like I don´t have a Photoshop for every picture or Word for every Wordfile. If things break, thats a pitty, but working with multiple versions of your tools is a similar pain. 
https://pnpm.js.org sounds a bit like a compromise; but I haven´t looked into it closely.

**Comment by davej** [comment]
Cool, I'll understand the use-case.

I think it's bad practice if you're working on a team but if you're working as an individual and willing to take the potential headaches of version mismatches between different projects then I can see how it makes sense.

I'll add this as a config option, I'll probably leave it undocumented for now though.

**Comment by davej** [comment]
Ok, as of [`v0.6.12`](https://github.com/pingyhq/pingy-cli/releases/tag/%40pingy%2Fcli%400.6.12), you can now use global modules. Just add `globalModuleSearch` to your `.pingy.json`.

```json
{
  "name": "my-site",
  "foo": "bar",
  "globalModuleSearch": true
}
```

There is also another way of doing this which doesn't require you to edit the `.pingy.json`. The workflow would look something like this:

```sh
npm install node-sass -g # Install node-sass globally
cd my-site # cd to your site
npm link node-sass # Will link to global node-sass
pingy dev # Uses global node-sass, no editing .pingy.json needed
```
