### ISSUE TITLE
Feature: Add support for redirects.

### ISSUE THREAD

**Issue by ladislavsulc** [pingyhq/pingy-cli#82]
Sometimes you want to create a static site with something like "portfolio" and its subpages - i.e. project-detail.html.

It would be great if we could achieve on localhost and in production nice URL's like:
- domain.com/portfolio
- domain.com/portfolio/project-1

Thank you!

**Comment by davej** [comment]
Thanks for the request. Will definitely consider this.

Prior art:
* https://surge.sh/help/adding-redirects
* https://www.netlify.com/docs/redirects/
* https://docs.ghost.org/v1/docs/redirects

**Comment by davej** [comment]
I will consider this for post-v1.0. Closing for the moment as I'm focusing on pre-v1.0 issues and bugs. Will revisit once 1.0 is released.
