### ISSUE TITLE
Support for Purify CSS

### ISSUE THREAD

**Issue by derevandal** [pingyhq/pingy-cli#83]
Today, many people use some css frameworks like Bulma and Bootstrap, but is hard to find someone site thats use 100% of some framework. So, we can use [Purify CSS](https://github.com/purifycss/purifycss) to remove unused css based on html.

**Comment by davej** [comment]
👍 Thanks, I will consider this for post-v1.0. Closing for the moment as I'm focusing on pre-v1.0 issues and bugs. Will revisit once 1.0 is released.
