### ISSUE TITLE
error on 'pingy dev'

### ISSUE THREAD

**Issue by flowen** [pingyhq/pingy-cli#84]
Would love to try, but I'm getting an error on High Sierra 10.13.2
node 9.2.1

look closeley:
![pingy](https://user-images.githubusercontent.com/4084169/34079820-7b9b1676-e335-11e7-8e13-a366b68afc5e.gif)

At the end you'll super quickly see an alert from OSX, it's the following:

![screen shot 2017-12-17 at 14 22 26](https://user-images.githubusercontent.com/4084169/34079830-bf169344-e335-11e7-8d65-9ae637ff2448.png)

I can't accept the incoming connection. Can I add this manually and what are the details?

error in console, though I'm pretty sure it's OSX:

(node:31030) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Could note require /Volumes/Data/DOCUMENTS/_htdocs/pingy2/node_modules/@pingy/accord/lib/adapters/typescript: Cannot find module 'typescript'
(node:31030) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by davej** [comment]
You can specify a port in `pingy.json`:
```json
{
  // ...
  port: 12345
}
```

Then you could add a rule to allow connections from `localhost:12345`.

Regarding the Typescript require error, see here: https://twitter.com/pambuk/status/941620510454091777

It looks like somebody has encountered the error before, they fixed the error by installing again with Yarn. I have not been able to reproduce the error myself (on Mac or Ubuntu). If you have a reproducible test case then let me know.

**Comment by davej** [comment]
Fixed in @pingy/cli@0.12.1
