### ISSUE TITLE
Export options

### ISSUE THREAD

**Issue by mazadah** [pingyhq/pingy-cli#87]
Is there a list of export options? I am looking for (combine js/css files) , (disable .map files) , (disable src files).

**Comment by davej** [comment]
Hi, Thanks for the issue :-)

> Is there a list of export options?

Not currently (apart from the README). Better docs are coming end of January

> I am looking for (combine js/css files)

Pingy purposely doesn't support this. They are an anti-pattern if your server supports HTTP/2. Check out a static host like [Netlify](https://www.netlify.com/), they do HTTP/2 and proper cache invalidation by default.

> (disable .map files)

```
{
    //...
    "sourceMap": false,
    //...
}
```

> (disable src files)

Not currently supported but take a look at #20 for a workaround.

**Comment by mazadah** [comment]
Thanks! :)
