### ISSUE TITLE
Extend the config file with '--no-open' option

### ISSUE THREAD

**Issue by mnasyrov** [pingyhq/pingy-cli#89]
Please add an option to `pingy.json` file which disables auto opening a browser.

**Comment by davej** [comment]
Not sure I want to do this, `.pingy.json` is supposed to describe only the website. Opening the website in a browser is a user preference. What I usually recommend it to use the `package.json` scripts field:

```
"scripts": {
  "start": "pingy dev --no-open",
  "export": "pingy export"
},
```

Then you can just run `npm start`.

I'll close for now but reconsider post v1.0.
