### ISSUE TITLE
SCSS @import files are not live reloading

### ISSUE THREAD

**Issue by mazadah** [pingyhq/pingy-cli#92]
Is there a way to make the imported files also watched? Edits to these files are not showing on browser unless I refresh the page, no live reloading. Only the main.scss file is watched.

**Comment by davej** [comment]
Are you on the latest version? There are tests for this so it should work. Can you restart pingy dev and see if it's still broken after a restart.

**Comment by mazadah** [comment]
I reinstalled pingy globally, now its working fine. Thx!
