### ISSUE TITLE
Export creates redundant dist subfolders

### ISSUE THREAD

**Issue by ladislavsulc** [pingyhq/pingy-cli#93]
Hi,

I am using the latest Pingy version (local) on WIN10. Whenever I do `pingy export` it creates a dist folder which is okay. Unfortunately, any other execution leads to export of the files into dist/dist and so on .... dist/dist/dist.

Any idea what might be causing this? Pingy.json is just a default set up.

```{
	"name": "whatever",
	"exportDir": "dist",
	"minify": true,
	"compile": true,
	"autoprefix": true,
	"exclusions": [
		{
			"path": "node_modules",
			"action": "exclude",
			"type": "dir"
		}
	],
	"port": 65525
}
```

Thank you.

**Comment by davej** [comment]
Do you have a repository that I can clone to try an reproduce this?

**Comment by ladislavsulc** [comment]
I have a private git over SSH but I will clone it to somewhere else to show you. Will let you know. Thank you.

**Comment by ladislavsulc** [comment]
Here: https://github.com/ladislavsulc/emphatic

**Comment by davej** [comment]
Figured this out. I wasn't converting the windows file path backslash in one place. Should be working now in `v0.12.5`

**Comment by ladislavsulc** [comment]
Thank you for fixing this. Love pingy! Have a nice day!
