### ISSUE TITLE
Config to export dist only contain needed files, folders?

### ISSUE THREAD

**Issue by huychau** [pingyhq/pingy-cli#95]
When I export website, all folder, files will be in `dist/`, but I need HTML, CSS, JS, images, fonts in this folder. No need *.pug, *.scss, etc. Any simple way to config? 

I know https://github.com/pingyhq/pingy-cli#configuring-export with `exclusions`, but I should config many objects. Please help  me simple way, thanks

**Comment by davej** [comment]
Dupe of #20
